# Generated by Django 4.2.7 on 2025-11-17 14:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Isotope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название изотопа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('half_life', models.FloatField(verbose_name='Период полураспада (лет)')),
                ('atomic_mass', models.FloatField(verbose_name='Атомная масса')),
                ('decay_type', models.CharField(max_length=100, verbose_name='Тип распада')),
                ('application', models.TextField(verbose_name='Применение')),
            ],
            options={
                'verbose_name': 'Изотоп',
                'verbose_name_plural': 'Изотопes',
            },
        ),
        migrations.CreateModel(
            name='CalculationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('DELETED', 'Удалён'), ('FORMED', 'Сформирован'), ('COMPLETED', 'Завершён'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=10, verbose_name='Статус заявки')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('time_elapsed', models.FloatField(default=0, verbose_name='Прошедшее время (лет)')),
                ('total_activity', models.FloatField(blank=True, null=True, verbose_name='Суммарная активность')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calculation_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка на расчет',
                'verbose_name_plural': 'Заявки на расчет',
            },
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField(default=1.0, verbose_name='Начальная масса (г)')),
                ('remaining_activity', models.FloatField(blank=True, null=True, verbose_name='Остаточная активность (Бк)')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_items', to='calculator.calculationorder', verbose_name='Заявка')),
                ('isotope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.isotope', verbose_name='Изотоп')),
            ],
            options={
                'verbose_name': 'Элемент расчета',
                'verbose_name_plural': 'Элементы расчета',
            },
        ),
        migrations.AddConstraint(
            model_name='calculationorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('client', 'status'), name='unique_draft_per_client'),
        ),
        migrations.AlterUniqueTogether(
            name='calculationitem',
            unique_together={('calculation', 'isotope')},
        ),
    ]
