# Generated by Django 4.2.7 on 2025-12-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isotope',
            options={'verbose_name': 'Изотоп', 'verbose_name_plural': 'Изотопы'},
        ),
    ]
