# Generated by Django 4.2.7 on 2025-12-12 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_isotope_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsotopeCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField(default=1.0, verbose_name='Начальная масса (г)')),
                ('remaining_activity', models.FloatField(blank=True, null=True, verbose_name='Остаточная активность (Бк)')),
                ('isotope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.isotope', verbose_name='Изотоп')),
            ],
            options={
                'verbose_name': 'Элемент расчета изотопов',
                'verbose_name_plural': 'Элементы расчета изотопов',
            },
        ),
        migrations.CreateModel(
            name='IsotopeCalculationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('DELETED', 'Удалён'), ('FORMED', 'Сформирован'), ('COMPLETED', 'Завершён'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=10, verbose_name='Статус заявки')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('time_elapsed', models.FloatField(default=0, verbose_name='Прошедшее время (лет)')),
                ('total_activity', models.FloatField(blank=True, null=True, verbose_name='Суммарная активность')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='isotope_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_isotope_orders', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка на расчет изотопов',
                'verbose_name_plural': 'Заявки на расчет изотопов',
            },
        ),
        migrations.RemoveField(
            model_name='calculationorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='calculationorder',
            name='moderator',
        ),
        migrations.DeleteModel(
            name='CalculationItem',
        ),
        migrations.DeleteModel(
            name='CalculationOrder',
        ),
        migrations.AddField(
            model_name='isotopecalculationitem',
            name='isotope_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isotope_items', to='calculator.isotopecalculationorder', verbose_name='Заявка на расчет изотопов'),
        ),
        migrations.AddConstraint(
            model_name='isotopecalculationorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('client', 'status'), name='unique_draft_per_client_isotope'),
        ),
        migrations.AlterUniqueTogether(
            name='isotopecalculationitem',
            unique_together={('isotope_order', 'isotope')},
        ),
    ]
